### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by DethByte64** [nain-F49FF806/anemo-aer#2]
### Describe what you'd like to see added to the app

Allow access to system files via root (if rooted)

**Comment by nain-F49FF806** [comment]
Thanks for sharing your idea. : Aer is not meant to be a general purpose file manager, only somewhere you store your private files. So I feel this functionality is outside of Aer's scope. 

## Alternate Solution:

For system files access you can use [Material Files](https://f-droid.org/en/packages/me.zhanghai.android.files/) instead which supports root.

To add Aer storage in Material files you can follow these steps  in Material Files app:

_Side Panel_ > Add Storage > External Storage > _Side panel_ > Aer

This will add a new folder to the side panel called simply "files", which is actually the root of Aer storage. 
You can rename it to "Aer" for convenience.

**Comment by nain-F49FF806** [comment]
Closing this now as the requested functionality is achievable through other foss apps and outside the scope of Aer. 
If the solution provided doesn't work, feel free to add a comment.
